language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: D7tsdAemH+ED+vzPbrn8fyWElQDP2EOoecPbYDQXbnp02L9C9V8eg/cVYd8X/lsoworVEr8EPrruuHpUTiTdBdXHIRZT4GNDKugzwHqUb1O8N5Isl8ySqzzs8X2jj+k9Bu4Kj+BYxAyvZ4dFQjdfhMfciI7yvF2loKLYjsnnAowP00L1NYLQoW2yoYiBjzHlhHtpUPSiX+nyULPmD4ehlKqqlXyxJxt4vEpzSYsugiIRHxBKmsn4X/I07MymQbg1ei4iW7rdcFqOoGhxojlBRNprCIF1DIncPFjxcMhnPnFgr6uaQ+IjjxXp95BzqiUfWHwLEoFybthHOR3067JfOB99qndolvrpLjoGEBZ/HcE3M1Ewn0att0TLXGPW5bcVUB9Sx7+lunvtkwMylSGhBhL/8eXFXcezIT+CKcKRXL/3ttxtUCmNwO4E4pswTdYjkQ4URJKZE5her3pkR7rix5/jk5e/NzHVKPmEp/fc+MA2B0dkmzhWWjXR0Bq9vfpwFZbApNVpjP7gc+1alKiZ6bBtF4YukWHkxF8POIsPKOxzoR8vzKIgFRL4DRzBcOgkMviihKFj2AWE4sRgwpIe9AcFtzpaua0bIpJProUR9PchUmB47GEiddzZ5U/Yxw8N0SGEQoBmvhojfdu1QLm2fJhTbtaFbFhO0rb4TQbgI/A=
  app: smoothie-social
  on:
    repo: Rigby33/smoothieSocial
